# Generated by Django 6.0.6 on 2026-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transportorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
